name: "plate-analyze"
config:
	topology.workers: 1
	
# spouts
spouts:
	- id: "plateAnalyzeSpout"
	  classname: "com.hakansel.pa.spout.PlateAnalyzeSpout"
	  parallelism: 1

# bolts
bolts:
	- id: "plateAnalyzeBolt"
	  classname: "com.hakansel.pa.spout.PlateAnalyzeBolt"
	  parallelism: 1
	  
	- id: "eventStoreBolt"
	  classname: "com.hakansel.pa.spout.EventStoreBolt"
	  parallelism: 1
	  
# streams
streams:
	- name: "plateAnalyzeSpout" --> "plateAnalyzeBolt"
	  from: "plateAnalyzeSpout"
	  to: "plateAnalyzeBolt"
	  grouping:
	  	type: FIELDS
	  	args: ["Plate"]
	  	
	- name: "plateAnalyzeBolt" --> "eventStoreBolt"
	  from: "plateAnalyzeBolt"
	  to: "eventStoreBolt"
	  grouping:
	  	type: SHUFFLE
	  	
	