name: "plate-analyze"
config:
    topology.workers: 1
	
# spouts
spouts:
    -   id: "plateAnalyzeSpout"
    classname: "com.hakansel.pa.spout.PlateAnalyzeSpout"
    constructorArgs:
        - "${pa.tcp.port}"
    parallelism: 1

# bolts
bolts:
	- id: "plateAnalyzeBolt"
	  classname: "com.hakansel.pa.spout.PlateAnalyzeBolt"
	  constructorArgs:
	  	- "${pa.plate.redlist}"
	  	- "${pa.plate.blacklist}"
	  configMethods:
	  	- name: "setLogInterval"
	  	  args:
	  		- "${pa.monitoring.time.interval}"
	  parallelism: 1
	  
	- id: "eventStoreBolt"
	  classname: "com.hakansel.pa.spout.EventStoreBolt"
	  constructorArgs:
	  	- "${pa.cassandra.host}"
	  	- "${pa.cassandra.keyspace}"
	  	- "${pa.cassandra.columnfamily}"
	  parallelism: 1

# streams
streams:
	- name: "plateAnalyzeSpout" --> "plateAnalyzeBolt"
	  from: "plateAnalyzeSpout"
	  to: "plateAnalyzeBolt"
	  grouping:
	  	type: SHUFFLE
	  	args: ["Plate"]
	  	
	- name: "plateAnalyzeBolt" --> "eventStoreBolt"
	  from: "plateAnalyzeBolt"
	  to: "eventStoreBolt"
	  grouping:
	  	type: SHUFFLE
	  	args: ["Event"]
	  	
	